{% set name = "is-number" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jacobtomlinson/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c856d3c9a90eafe9503267f3ad9ab278cf846e4ba7ef660f9f42a707fe79ea10

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - is_number

about:
  home: https://github.com/jacobtomlinson/is-number
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library to determine if something is a number.
  description: |
    A Python library to determine if something is a number.
  doc_url: https://github.com/jacobtomlinson/is-number
  dev_url: https://github.com/jacobtomlinson/is-number

extra:
  recipe-maintainers:
    - jacobtomlinson
